language: node_js
node_js:
  - "10.4.1"
sudo: true

addons:
  chrome: stable

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng lint
  - ng test  --watch false --browsers ChromeHeadless
  - ng e2e --protractor-config="e2e/protractor.ci.conf.js"
  - ng build --prod --base-href $base_href

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/adder
  on:
    branch: master