language: node_js
node_js:
  - "10.4.1"
sudo: true

addons:
  chrome: stable

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - yarn lint
  - yarn test  --watch false --browsers ChromeHeadless
  - yarn e2e_ci
  - yarn build --prod --base-href $base_href

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/adder
  on:
    branch: master